# Generated by Django 5.0.3 on 2024-04-06 04:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
