# Generated by Django 5.0.3 on 2024-04-06 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_img_post_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_uploaded',
            new_name='date',
        ),
    ]
